In [1]:
import numpy as np


In [2]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Nikku28/anaconda3/Library/include
    lib directory: C:/Users/Nikku28/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [5]:
# %run 'python -c "import numpy; numpy.info(numpy.add)"'

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
Z = np.arange(50)
Z = Z[ ::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [8]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [10]:
Z = np.eye(3)
print(Z)





[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.64954102 0.22635251 0.83139585]
  [0.76957699 0.56529565 0.42980962]
  [0.1104461  0.42248804 0.29256649]]

 [[0.60315074 0.8092916  0.33917996]
  [0.97508846 0.19496943 0.90755001]
  [0.87721831 0.88308238 0.47701825]]

 [[0.19091188 0.90926019 0.65028536]
  [0.47913768 0.43246361 0.36916897]
  [0.12720477 0.60482539 0.09447065]]]


In [12]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.029598447493376367 0.9934400870707278


In [13]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.6163749850502894


In [14]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width = 1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


In [17]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [20]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
Z = np.random.random((5,5))
Z = (Z-np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.5737009   1.2215652  -1.629812   -1.64236374  1.06994364]
 [ 0.28178276  0.13134409 -1.48460661 -1.46182203  0.10508828]
 [ 1.1262467   0.89514088  1.44588306  1.41663286  0.70007131]
 [-0.57100082 -0.93070676 -0.44520602 -1.25758075 -1.26968614]
 [ 0.1748245   0.71825092 -0.08413023  0.36663954  0.54980044]]


In [22]:
color = np.dtype([("r", np.ubyte, 1), 
                  ("g", np.ubyte, 1), 
                  ("b", np.ubyte, 1), 
                  ("a", np.ubyte, 1)])
                 

C:\Users\Nikku28\AppData\Local\Temp\ipykernel_16092\4273720647.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [23]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution 
Z=np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [24]:
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [25]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5),-1))

9
10


In [30]:
Z**Z
2 <<z >>2
Z <- Z
1j *Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [26]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Nikku28\AppData\Local\Temp\ipykernel_16092\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Nikku28\AppData\Local\Temp\ipykernel_16092\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Nikku28\AppData\Local\Temp\ipykernel_16092\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [27]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-2. -4.  7.  5.  3. -9.  2. -9.  6.  2.]


In [28]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1, Z2))

[2 7 8 9]


In [29]:
defaults = np.seterr(all="igmore")
Z = np.ones(1) / 0

- = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
Z = np.ones(1)/0

SyntaxError: invalid syntax (397898606.py, line 4)

In [30]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Nikku28\AppData\Local\Temp\ipykernel_16092\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [31]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [32]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [33]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

In [34]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[0. 2. 5. 7. 8. 6. 2. 9. 6. 2.]
[0. 2. 5. 7. 8. 6. 2. 9. 6. 2.]
[0. 2. 5. 7. 8. 6. 2. 9. 6. 2.]
[0 2 5 7 8 6 2 9 6 2]
[0. 2. 5. 7. 8. 6. 2. 9. 6. 2.]


In [35]:
Z = np.zeros((5,5))
Z+= np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [36]:
def generate() :
    for x in range(10) :
        yield x
Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [37]:
Z = np.linspace(0,1,11, endpoint=False) [1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [38]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.15060135 0.22367159 0.25213413 0.42544354 0.51631352 0.52842271
 0.55012964 0.70718591 0.85622874 0.99279181]


In [39]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [40]:
# COnsider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


In [41]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [42]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.81246144 0.88226862 0.9841846  0.95403491 1.00852798 0.93488839
 0.87275385 0.91560926 1.12608842 0.75202403]
[0.51477267 0.77916092 1.52003543 0.80456092 0.33521365 1.43575822
 1.44477661 1.1931332  0.70200967 1.37400415]


In [43]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.25308582 0.         0.09023364 0.76690698 0.87641711 0.05725115
 0.56353941 0.67484037 0.90656476 0.0164588 ]


In [44]:
Z = np.zeros((5,5), [('x' , float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [45]:
X = np.arange(8)
Y = X+0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [46]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [64]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [47]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

96


In [48]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Nikku28\AppData\Local\Temp\ipykernel_16092\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [68]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.75422381 0.78681516 1.07636107 0.66324135 0.09765242
  0.34686097 0.55113786 0.25035143 0.73175467]
 [0.75422381 0.         0.19544262 0.32545421 0.52431288 0.83704824
  0.71393343 0.22911283 0.78519464 0.14075255]
 [0.78681516 0.19544262 0.         0.40077561 0.37590799 0.85492305
  0.82781646 0.35963504 0.87424063 0.07316313]
 [1.07636107 0.32545421 0.40077561 0.         0.77618342 1.16119193
  0.99348917 0.5324086  1.08266391 0.40427389]
 [0.66324135 0.52431288 0.37590799 0.77618342 0.         0.69222529
  0.85918676 0.54417023 0.84760199 0.39112143]
 [0.09765242 0.83704824 0.85492305 1.16119193 0.69222529 0.
  0.42968365 0.64129801 0.31792253 0.80417662]
 [0.34686097 0.71393343 0.82781646 0.99348917 0.85918676 0.42968365
  0.         0.48561178 0.13271308 0.75729644]
 [0.55113786 0.22911283 0.35963504 0.5324086  0.54417023 0.64129801
  0.48561178 0.         0.55714536 0.28649162]
 [0.25035143 0.78519464 0.87424063 1.08266391 0.84760199 0.31792253
  0.13271308 0.55714

In [49]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [50]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [51]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / (2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [52]:
n= 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [53]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[ 0.28876782  0.15202341  0.23737502 -0.24932931 -0.26522019 -0.17753915
   0.36134099 -0.21412363  0.04577825 -0.1790732 ]
 [ 0.0699097   0.18662548 -0.29221053 -0.15438648 -0.23541488 -0.03052429
   0.41263146  0.50908958 -0.4178024  -0.04791765]
 [-0.25930236 -0.11840878 -0.3080988  -0.04003572  0.4886229  -0.27237832
   0.28487442 -0.2570866   0.41873206  0.06308121]
 [ 0.03727838  0.47153299  0.41079004  0.05415966 -0.17822015 -0.1117842
  -0.07966162 -0.18205144 -0.27142822 -0.15061544]
 [-0.419496    0.11183425 -0.18079328 -0.3853651  -0.49947572  0.34695567
   0.19008354  0.25319142  0.18000717  0.40305805]]


In [54]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


[[7 6 7]
 [1 4 4]
 [8 0 9]]
[[8 0 9]
 [1 4 4]
 [7 6 7]]


In [55]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [56]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.45395661517157226


In [57]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B, None])
for x,y,z in it:z[...] = x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [58]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)
    

range_10


In [59]:
Z = np.ones(10)
I = np.random.randint(0,len(Z), 20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[3. 1. 5. 2. 5. 4. 3. 3. 2. 2.]
[5. 1. 9. 3. 9. 7. 5. 5. 3. 3.]


In [60]:
X = [1,2,3,4,5,6]
I = [1,2,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 2. 4. 5. 0. 0. 0. 0. 3.]


In [61]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [62]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[50 56 43 58]
 [53 33 49 60]
 [47 34 51 62]]
[[50 56 43 58]
 [53 33 49 60]
 [47 34 51 62]]


In [63]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.39056944 0.5092117  0.58712473 0.48789812 0.47050831 0.63998639
 0.44865673 0.42537589 0.58991208 0.45410096]
0    0.390569
1    0.509212
2    0.587125
3    0.487898
4    0.470508
5    0.639986
6    0.448657
7    0.425376
8    0.589912
9    0.454101
dtype: float64


In [64]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))
np.sum(A*B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([0.6004819 , 0.66839572, 1.17937872, 0.62095209, 2.09020613])

In [65]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [66]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [67]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [69]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1), -1, axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0', F.dtype), ('p1', F.dtype)] )
G = np.unique(G)
print(G)

[( 4,  8) ( 4, 17) ( 8, 17) ( 9, 21) ( 9, 30) ( 9, 56) ( 9, 60) (15, 32)
 (15, 36) (15, 73) (15, 76) (17, 26) (17, 49) (21, 30) (23, 26) (23, 96)
 (26, 49) (26, 96) (28, 39) (28, 47) (28, 59) (28, 63) (31, 63) (31, 92)
 (32, 76) (36, 73) (39, 63) (47, 59) (56, 60) (63, 92)]


In [70]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [71]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n -1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [73]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window+1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [74]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.49775286,  0.50784098, -0.89681538, -0.27320476,  0.56916   ,
       -0.27624197,  0.74980352, -0.34717856, -0.49445716,  0.33458108,
       -0.60878552,  0.1374897 ,  0.23244788, -0.08841094,  0.67275811,
        0.85371219, -0.92300955, -0.8734372 ,  0.53022238,  0.25216556,
        0.05443706,  0.17649953,  0.51985477, -0.3257714 , -0.57167632,
       -0.37286533, -0.91025879,  0.10890402,  0.5400062 ,  0.22555499,
        0.40079658,  0.15899154,  0.64345136, -0.65616635, -0.06263834,
       -0.05114037, -0.96119985, -0.60581533, -0.5059241 , -0.76065791,
       -0.48991731, -0.15317134,  0.5965052 ,  0.11632079,  0.86791089,
       -0.42765879, -0.89512903,  0.88236321,  0.15661627,  0.30263096,
       -0.40115321, -0.44637688,  0.19706848, -0.11706396, -0.52876418,
        0.24586768, -0.36888658,  0.93514561,  0.59057113, -0.65911169,
        0.5556869 , -0.57464078, -0.09664196, -0.82686463,  0.39362824,
       -0.34033958,  0.68229052, -0.5436148 , -0.07841016,  0.16

In [79]:
def distance(P0, P1, P):
   T =  P1-P0
   L = (T**2).sum(axis=1)
   U = -((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1])/L
   U = U.reshape(len(U),1)
   D = P0 + U*T - p
   return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))
    

[11.66124909  7.38458912  1.01768241  3.23565867  9.25524634  2.94494957
  5.20187793  1.25178676  8.05143109  7.04310277]


In [80]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389 0.27517898 1.32255477 7.02357523]
 [5.43676675 4.27257485 1.83943103 4.58959432 7.18140892 4.30508895
  5.92942389

In [85]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [86]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [87]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular value decomposition
rank = np.sum(S> 1e-10)
print(rank)


10


In [88]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


In [89]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1+ (Z.shape[0]-3)
j = 1+ (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i,j,n,n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 2]
   [1 4 2]
   [3 3 2]]

  [[4 2 2]
   [4 2 1]
   [3 2 4]]

  [[2 2 3]
   [2 1 4]
   [2 4 2]]

  [[2 3 0]
   [1 4 4]
   [4 2 0]]

  [[3 0 3]
   [4 4 4]
   [2 0 0]]

  [[0 3 3]
   [4 4 0]
   [0 0 4]]

  [[3 3 3]
   [4 0 4]
   [0 4 0]]

  [[3 3 4]
   [0 4 4]
   [4 0 1]]]


 [[[1 4 2]
   [3 3 2]
   [0 2 4]]

  [[4 2 1]
   [3 2 4]
   [2 4 4]]

  [[2 1 4]
   [2 4 2]
   [4 4 1]]

  [[1 4 4]
   [4 2 0]
   [4 1 1]]

  [[4 4 4]
   [2 0 0]
   [1 1 4]]

  [[4 4 0]
   [0 0 4]
   [1 4 1]]

  [[4 0 4]
   [0 4 0]
   [4 1 3]]

  [[0 4 4]
   [4 0 1]
   [1 3 0]]]


 [[[3 3 2]
   [0 2 4]
   [1 1 4]]

  [[3 2 4]
   [2 4 4]
   [1 4 1]]

  [[2 4 2]
   [4 4 1]
   [4 1 4]]

  [[4 2 0]
   [4 1 1]
   [1 4 1]]

  [[2 0 0]
   [1 1 4]
   [4 1 0]]

  [[0 0 4]
   [1 4 1]
   [1 0 0]]

  [[0 4 0]
   [4 1 3]
   [0 0 2]]

  [[4 0 1]
   [1 3 0]
   [0 2 4]]]


 [[[0 2 4]
   [1 1 4]
   [3 0 4]]

  [[2 4 4]
   [1 4 1]
   [0 4 1]]

  [[4 4 1]
   [4 1 4]
   [4 1 1]]

  [[4 1 1]
   [1 4 1]
   [1 1 4]]

  [[1 1 4]
   

In [94]:
# note : Only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
    
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  9  7 17  9]
 [ 9  7 10 16 11]
 [ 7 10  2 42  5]
 [17 16 42  3  2]
 [ 9 11  5  2  8]]


In [96]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [99]:
Z = np.ones((16,16))
K = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0],K), axis = 0),np.arange(0,Z.shape[1],K),axis=1)
print(S)
                   

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [100]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [101]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

#slow
print(Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


In [103]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))
    

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [104]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [105]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

In [106]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 6 7]


In [107]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 0 4]
 [2 3 4]
 [4 2 3]
 [3 4 4]
 [4 2 0]
 [0 0 1]
 [4 2 1]
 [2 3 1]
 [0 1 0]
 [2 4 0]]
[[3 0 4]
 [2 3 4]
 [4 2 3]
 [3 4 4]
 [4 2 0]
 [0 0 1]
 [4 2 1]
 [2 3 1]
 [0 1 0]
 [2 4 0]]
[[3 0 4]
 [2 3 4]
 [4 2 3]
 [3 4 4]
 [4 2 0]
 [0 0 1]
 [4 2 1]
 [2 3 1]
 [0 1 0]
 [2 4 0]]


In [108]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [109]:

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


In [110]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.18601991, 0.09366664, 0.08294063, 0.12220999, 0.16523563,
        0.10009306, 0.06055641, 0.18851114, 0.03215537, 0.19090249],
       [0.41235854, 0.20763496, 0.18385815, 0.27090827, 0.36628512,
        0.2218807 , 0.13423808, 0.41788097, 0.07128022, 0.42318197],
       [0.58333375, 0.29372614, 0.26009081, 0.3832343 , 0.51815702,
        0.31387855, 0.18989688, 0.59114592, 0.10083497, 0.59864487],
       [0.68725662, 0.34605444, 0.30642686, 0.45150878, 0.61046844,
        0.36979707, 0.22372765, 0.69646056, 0.11879906, 0.70529548],
       [0.53151098, 0.26763181, 0.23698461, 0.34918815, 0.47212448,
        0.2859939 , 0.17302663, 0.53862913, 0.09187689, 0.54546188],
       [0.52163676, 0.26265984, 0.232582  , 0.34270107, 0.46335352,
        0.28068081, 0.16981221, 0.52862267, 0.09017004, 0.53532849],
       [0.0134548 , 0.0067749 , 0.00599909, 0.00883944, 0.01195148,
        0.00723972, 0.00438004, 0.01363499, 0.00232579, 0.01380796],
       [0.24372453, 0.12272265, 0.1086693

In [111]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [112]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [113]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21620696  0.17658821]
